name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # x86_64 — only arch supported right now

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build library
        run: make
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & run benchmark
        run: |
          make
          make bench

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          make
          make test