name: C Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler tools
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Build project
        run: make

      - name: Run executable
        run: ./main